const qa = window.__ledgerTest, checks = [], delay = ms => new Promise(r => setTimeout(r, ms));
const assert = (value, message) => { if (!value) throw new Error(message); checks.push(message); };
const wait = async (predicate, message) => { for (let i=0;i<200;i++) { if (predicate()) return; await delay(30); } throw new Error(message); };
await wait(()=>qa.ledger?.getState, 'Application did not initialize');
const state = qa.ledger.getState();
assert(state.cases.length === 0 && state.assets.length === 0 && state.findings.length === 0, 'Fresh installation contains no sample records');
assert(document.title.includes('Notechain') && document.querySelector('.notebook-brand')?.textContent === '链迹笔记', 'Product name and Chinese brand render');
assert(document.querySelector('.notebook-brand img')?.naturalWidth > 0, 'Product icon loads');
const platform = (await qa.invoke('runtime_info')).platform;
assert(platform === expectedPlatform, 'Correct native runtime');
const caseId = qa.ledger.addCase({name:'Runtime check',code:'QA',summary:'',priority:'low',tags:[]});
const category = qa.ledger.addTarget({name:'Category',kind:'',identifier:'',note:''},caseId);
const at = new Date().toISOString();
const asset = title => ({caseId,title,kind:'url',value:'https://example.test/',targetId:category,status:'confirmed',severity:'low',confidence:'high',tags:[],situation:'',utility:'',nextSteps:'',details:'',provenance:{source:'runtime check',method:'test',reason:'',capturedAt:at},noteMarkdown:'## 中文笔记\n\n**粗体**和 `code`。\n\n'+Array.from({length:60},(_,i)=>`第 ${i} 段。`).join('\n\n')});
const id = qa.ledger.addAsset(asset('Note'));
await delay(100); await qa.flush(); qa.navigate(`/cases/${caseId}/assets/${id}`);
await wait(()=>document.querySelector(`[data-asset-id="${id}"] .tiptap`), 'Editor did not open');
let editor = document.querySelector('.tiptap');
assert(editor.textContent.includes('中文笔记') && editor.querySelector('strong') && editor.querySelector('code'), 'Chinese Markdown renders');
editor.focus(); const range=document.createRange(); range.selectNodeContents(editor.querySelector('p')); range.collapse(false); getSelection().removeAllRanges(); getSelection().addRange(range);
document.execCommand('insertText',false,' 保存验证');
await delay(700); await qa.flush();
assert((await qa.invoke('read_body',{kind:'assets',id})).includes('保存验证'), 'Editor writes to native SQLite');
const image = await qa.invoke('import_image',{bytes:Array.from(Uint8Array.from(atob(fixtureImage),c=>c.charCodeAt(0))),name:'icon.png'});
const another = await qa.invoke('import_image',{bytes:Array.from(Uint8Array.from(atob(fixtureImage),c=>c.charCodeAt(0))),name:'duplicate.png'});
assert(image.src === another.src, 'Images deduplicate');
qa.ledger.updateAsset(id,{noteMarkdown:(await qa.invoke('read_body',{kind:'assets',id}))+`\n\n![image](${image.src})`});
editor.blur(); await delay(250); await qa.flush();
await wait(()=>document.querySelector('.managed-image img'), 'Image element missing');
document.querySelector('.managed-image img').scrollIntoView({block:'center'});
await wait(()=>document.querySelector('.managed-image img')?.naturalWidth === 128, 'Native image protocol failed');
assert(true,'Native image protocol renders');
let rejected=false; try { await qa.invoke('read_image',{src:'/attachments/../../private.txt'}); } catch { rejected=true; }
assert(rejected,'Image traversal rejected');
const secretId = qa.ledger.addFinding({caseId,sourceAssetId:id,title:'Secret',type:'secret',value:'RUNTIME_TEST_ONLY',severity:'low',confidence:'low',status:'suspected',sourceLocation:`/cases/${caseId}/assets/${id}`,howFound:'',whySearched:'',payload:'',principle:'',impact:'',limitations:'',noteMarkdown:''});
qa.ledger.updateAsset(id,{noteMarkdown:(await qa.invoke('read_body',{kind:'assets',id}))+`\n\n[Secret](/cases/${caseId}/findings/${secretId})`});
await delay(250); await qa.flush();
await wait(()=>document.querySelector('.notebook-secret-node')?.textContent.includes('********'),'Secret mask missing');
assert(!document.querySelector('.tiptap').textContent.includes('RUNTIME_TEST_ONLY'),'Secrets are masked');
const reader=document.querySelector('.asset-reader'); reader.scrollTop=700; reader.dispatchEvent(new Event('scroll')); await delay(750); await qa.flush();
assert((await qa.invoke('load_index')).state.reading[id]?.offsetPx > 0,'Reading position persists');
const captured = qa.ledger.captureText({id:'runtime_capture',text:'中文收集内容'});
await delay(100); await qa.flush();
assert(qa.ledger.getState().assets.some(a=>a.id===captured.id),'Transfer capture creates a linked source asset');
assert(document.querySelector('.transfer-drawer'),'In-app transfer tray available');
await qa.invoke('qa_pdf',{html:`<h1>中文 PDF</h1><img src="asset-ledger://app${image.src}">`+Array.from({length:80},(_,i)=>`<p>第 ${i} 行分页验证。</p>`).join('')});
assert(true,'Native PDF export completes');
const call = input=>qa.invoke('notebook',{input});
const opened=await call({action:'open',kind:'notebook',selectedPath:fixtureDirectory+'/Notebook'}), book=opened.notebook.id;
const entries=await call({action:'children',id:book,path:'Category/Nested'});
assert(entries[0].path==='Category/Nested/中文 [1].md','Nested notebook path preserves Unicode');
qa.navigate('/notebooks/'+book+'?file='+encodeURIComponent(entries[0].path));
await wait(()=>document.querySelector('[data-file-path] .tiptap')?.textContent.includes('文件笔记'),'File editor missing');
assert(!document.querySelector('.asset-architecture'),'Notebook mode opens the editor without asset overview');
const note=await call({action:'read',id:book,path:entries[0].path});
await call({action:'save',id:book,path:entries[0].path,revision:note.revision,content:'# 更新内容\n'});
assert((await call({action:'read',id:book,path:entries[0].path})).content.includes('更新内容'),'Markdown saves to the selected file');
await wait(()=>document.querySelector('.tiptap')?.textContent.includes('更新内容'),'File watcher did not refresh');
assert(true,'File watcher refreshes the clean document');
await qa.flush();
return {checks,caseId,id,book,platform};
