const qa=window.__ledgerTest, checks=[], delay=ms=>new Promise(r=>setTimeout(r,ms));
const assert=(value,message)=>{if(!value)throw new Error(message);checks.push(message)};
const wait=async(predicate,message)=>{for(let i=0;i<200;i++){if(predicate())return;await delay(30)}throw new Error(message)};
const errors=[];const failed=event=>errors.push(event.detail);window.addEventListener('ledger-storage-error',failed);
const call=input=>qa.invoke('notebook',{input});
const open=async path=>{window.dispatchEvent(new Event('ledger-flush-editors'));await qa.flush();qa.navigate('/notebooks/'+bookId+'?file='+encodeURIComponent(path));await wait(()=>document.querySelector('[data-file-path="'+path+'"] .tiptap')?.editor,'File editor missing: '+path);await delay(100);return document.querySelector('[data-file-path="'+path+'"] .tiptap').editor};
let editor=await open('Examples/图片兼容.md');
await wait(()=>document.querySelectorAll('.managed-image').length===4,'Obsidian / Typora images were not parsed');
for(const image of document.querySelectorAll('.managed-image img')) image.scrollIntoView({block:'center'});
await wait(()=>document.querySelectorAll('.managed-image img').length===4&&[...document.querySelectorAll('.managed-image img')].every(img=>img.naturalWidth===128),'Compatible images did not resolve');
assert(true,'Obsidian wiki images, dimensions, Typora spaced paths and HTML images display');
assert(!(await call({action:'children',id:bookId,path:''})).some(entry=>entry.name==='assets'),'Image-only folders stay out of note categories');
editor.commands.focus('end');
const transfer=new DataTransfer();transfer.items.add(new File([Uint8Array.from(atob(fixtureImage),c=>c.charCodeAt(0))],'pasted.png',{type:'image/png'}));
editor.view.dom.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,cancelable:true,clipboardData:transfer}));
await wait(()=>document.querySelectorAll('.managed-image').length===5,'Pasted image missing');
const reader=document.querySelector('.file-reader');reader.scrollTop=reader.scrollHeight;reader.dispatchEvent(new Event('scroll'));await delay(850);window.dispatchEvent(new Event('ledger-flush-editors'));await qa.flush();
const savedImages=await call({action:'read',id:bookId,path:'Examples/图片兼容.md'});
assert(savedImages.content.includes('![[Pasted image 20260922114737.png]]')&&savedImages.content.includes('attachments/'),'Image paste preserves wiki syntax and saves the new attachment');
assert(savedImages.content.includes('width="180"'),'Editing retains Typora HTML image dimensions');
assert(!(await call({action:'children',id:bookId,path:'Examples'})).some(entry=>entry.name==='attachments'),'Pasted image directory is hidden from the note tree');
assert(errors.length===0,'Image paste and scroll do not poison native preference saves');

editor=await open('Examples/语法.md');
const type=async text=>{
  editor.commands.setContent('<p></p>');editor.commands.focus('end');await delay(40);
  for(const char of text){const{from,to}=editor.state.selection;let handled=false;editor.view.someProp('handleTextInput',fn=>{if(fn(editor.view,from,to,char,()=>editor.view.state.tr.insertText(char,from,to)))handled=true;return handled});if(!handled)editor.view.dispatch(editor.state.tr.insertText(char,from,to));}
  await delay(50);
};
for(const [source,selector,text] of [['`hi`','code','hi'],['前**重点**','strong','重点'],['****重点****','strong','重点'],['***重点***','strong em, em strong','重点'],['``a`b``','code','a`b'],['~~删除~~','s','删除']]){
  await type(source);assert(editor.view.dom.querySelector(selector)?.textContent===text,'Typing renders '+source);
}
editor.commands.setContent('<p></p>');editor.commands.focus('end');
const inputChar=char=>{const{from,to}=editor.state.selection;let handled=false;editor.view.someProp('handleTextInput',fn=>{if(fn(editor.view,from,to,char,()=>editor.view.state.tr.insertText(char,from,to)))handled=true;return handled});if(!handled)editor.view.dispatch(editor.view.state.tr.insertText(char,from,to))};
inputChar('*');inputChar('*');assert(editor.state.doc.textContent==='****','Two stars auto-complete a bold pair');inputChar('中文');inputChar('*');inputChar('*');await delay(80);assert(editor.view.dom.querySelector('strong')?.textContent==='中文','Auto-completed bold pair renders after closing');
editor.commands.setContent('<p></p>');editor.commands.focus('end');inputChar('*');inputChar('*');const boldPaste=new DataTransfer();boldPaste.setData('text/plain','中文');editor.view.dom.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,cancelable:true,clipboardData:boldPaste}));inputChar('*');inputChar('*');await delay(80);assert(editor.view.dom.querySelector('strong')?.textContent==='中文','Auto-completed bold pair also closes after pasted text');
const enter=()=>editor.view.dom.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',bubbles:true,cancelable:true}));
await type('`hi`');enter();await delay(60);
assert(editor.state.selection.$from.parent.type.name==='paragraph'&&!(editor.state.storedMarks??editor.state.selection.$from.marks()).some(mark=>mark.type.name==='code'),'A new paragraph after inline code is ordinary text');
for(const [pair,inside,selector] of [['``',1,'code'],['****',2,'strong'],['******',3,'strong em, em strong']]){
  editor.commands.setContent('<p></p>');editor.commands.insertContent({type:'text',text:pair});editor.commands.setTextSelection(1+inside);editor.commands.focus();await delay(40);
  const{from,to}=editor.state.selection;let handled=false;editor.view.someProp('handleTextInput',fn=>{if(fn(editor.view,from,to,'中文',()=>editor.view.state.tr.insertText('中文',from,to)))handled=true;return handled});if(!handled)editor.view.dispatch(editor.state.tr.insertText('中文',from,to));
  assert(editor.view.dom.querySelector(selector)?.textContent==='中文','Filling a pre-existing '+pair+' pair renders without escaping');
  assert(editor.getMarkdown().includes('中文')&&!editor.getMarkdown().includes('\\'),'Pair input is saved as Markdown, not escaped literal text');
}
editor.commands.setContent('<p></p>');editor.commands.insertContent({type:'text',text:'`中文`'});editor.commands.setTextSelection(4);editor.commands.focus();await delay(40);
editor.view.dom.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'中文'}));await delay(80);
assert(editor.view.dom.querySelector('code')?.textContent==='中文','Composition completion renders text inside an existing pair');
editor.commands.setContent('<p><code>`literal`</code></p>');editor.commands.setTextSelection(4);editor.commands.focus();await delay(30);
editor.view.dom.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:''}));await delay(80);
assert(editor.view.dom.querySelector('code')?.textContent==='`literal`','Existing code contents are not reinterpreted as Markdown');
await type('**** ');assert(editor.view.dom.querySelector('hr'),'A standalone four-star line renders as a separator');
editor.commands.setContent('<p></p>');editor.commands.focus('end');await delay(30);
const md='**中文加粗**与``a`b``\n\n- [x] 完成\n- [ ] 待办\n\n| 项目 | 数值 |\n| --- | --- |\n| 示例 | 42 |';
const pasted=new DataTransfer();pasted.setData('text/plain',md);editor.view.dom.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,cancelable:true,clipboardData:pasted}));
await wait(()=>editor.view.dom.querySelector('table')&&editor.view.dom.querySelector('strong'),'Markdown paste did not render');
assert(editor.view.dom.querySelector('code')?.textContent==='a`b'&&editor.view.dom.querySelector('input[type=checkbox]'),'Markdown paste renders code, bold, tasks and tables');
await delay(600);window.dispatchEvent(new Event('ledger-flush-editors'));await qa.flush();
const syntax=await call({action:'read',id:bookId,path:'Examples/语法.md'});
assert(syntax.content.includes('``a`b``'),'Code containing backticks serializes with a safe delimiter');
const strongStyle=getComputedStyle(editor.view.dom.querySelector('strong')).fontWeight;
assert(Number(strongStyle)>=760,'Rendered bold text uses a visibly heavier font weight');

editor=await open('Examples/目标.md');const assetsBefore=qa.ledger.getState().assets.length;
let term;editor.state.doc.descendants((node,pos)=>{if(node.isText&&node.text.includes('幂等性'))term=pos+node.text.indexOf('幂等性')});
editor.commands.focus();await delay(30);editor.commands.setTextSelection({from:term,to:term+3});
editor.view.dom.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true,clientX:420,clientY:230}));
await wait(()=>document.querySelector('[role=menu][aria-label=正文操作]'),'Explanation context menu missing');
[...document.querySelectorAll('[role=menuitem]')].find(button=>button.textContent==='添加扩展解释').click();
await wait(()=>document.querySelector('[data-kind=explanation][data-mode=expanded] .tiptap')?.editor,'Explanation editor did not expand');
const explanation=document.querySelector('[data-kind=explanation] .tiptap').editor;
explanation.commands.setContent('同一个请求重复执行，结果与执行一次相同。\n\n例如：用同一个 `requestId` 重试创建订单，不会生成第二份订单。',{contentType:'markdown'});
await delay(700);document.querySelector('[aria-label=关闭预览]').click();await delay(280);await qa.flush();
const note=await call({action:'read',id:bookId,path:'Examples/目标.md'});
assert(note.content.includes('notechain-explanation-')&&decodeURIComponent(note.content).includes('不会生成第二份订单'),'Explanation body persists inside its owning Markdown note');
assert(qa.ledger.getState().assets.length===assetsBefore,'Adding an explanation does not create an asset or article');
await open('Examples/来源.md');editor=await open('Examples/目标.md');
let chip=editor.view.dom.querySelector('a[data-notebook-link]');
chip.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,clientX:440,clientY:230}));
await wait(()=>document.querySelector('[data-kind=explanation][data-mode=compact]')?.textContent.includes('结果与执行一次相同'),'Saved explanation preview is missing');
document.querySelector('[aria-label=展开预览]').click();await wait(()=>document.querySelector('[data-kind=explanation][data-mode=expanded] .tiptap'),'Reopened explanation did not expand');
assert(!document.querySelector('[data-kind=explanation] [aria-label=打开关联笔记]'),'Explanation does not pretend to have a separate source article');
document.querySelector('[aria-label=关闭预览]').click();await delay(280);

editor=await open('Examples/来源.md');editor.commands.focus();await delay(30);
let paragraph;editor.state.doc.descendants((node,pos)=>{if(node.isText&&node.text.startsWith('消息队列按'))paragraph={from:pos,to:pos+node.nodeSize}});
editor.commands.setTextSelection(paragraph);await delay(50);document.querySelector('[aria-label=加入中转站]').click();
editor=await open('Examples/目标.md');editor.commands.focus('end');await delay(70);
document.querySelector('[aria-label=打开中转]').click();await delay(60);document.querySelector('.transfer-clip').click();
await wait(()=>editor.view.dom.querySelector('a[data-notebook-target^="/notebooks/"]'),'File reference was not inserted');
await delay(700);await qa.flush();
let sourceLink=editor.view.dom.querySelector('a[data-notebook-target^="/notebooks/"]');const originalHref=sourceLink.getAttribute('data-notebook-target');
assert(decodeURIComponent(originalHref).includes('Examples/来源.md'),'Tray insertion retains the original file target');
sourceLink.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,clientX:450,clientY:260}));
await wait(()=>document.querySelector('[data-kind=file]')?.textContent.includes('先进先出'),'Transferred file note has no preview');
document.querySelector('[aria-label=展开预览]').click();await wait(()=>document.querySelector('[data-kind=file] .tiptap')?.editor,'File source editor did not expand');
const sourceEditor=document.querySelector('[data-kind=file] .tiptap').editor;
sourceEditor.commands.focus('end');sourceEditor.commands.insertContent(' 来源预览中补充。');await delay(650);document.querySelector('[aria-label=关闭预览]').click();await delay(280);await qa.flush();
assert((await call({action:'read',id:bookId,path:'Examples/来源.md'})).content.includes('来源预览中补充'),'Expanded file preview edits the source file');
editor=document.querySelector('[data-file-path="Examples/目标.md"] .tiptap').editor;
let reference;editor.state.doc.descendants((node,pos)=>{if(node.marks.some(mark=>mark.type.name==='link'&&mark.attrs.href===originalHref))reference={from:pos,to:pos+node.nodeSize}});
editor.commands.focus();await delay(30);editor.commands.setTextSelection(reference);await delay(50);document.querySelector('[aria-label=加入中转站]').click();
editor=await open('Examples/第二份.md');editor.commands.focus('end');await delay(70);document.querySelector('[aria-label=打开中转]').click();await delay(60);document.querySelector('.transfer-clip').click();
await wait(()=>editor.view.dom.querySelector('a[data-notebook-target^="/notebooks/"]'),'Restaged reference missing');await delay(650);await qa.flush();
const restaged=editor.view.dom.querySelector('a[data-notebook-target^="/notebooks/"]');
assert(restaged.getAttribute('data-notebook-target')===originalHref,'A restaged link keeps its source instead of linking to the intermediate note');
restaged.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,clientX:450,clientY:260}));
await wait(()=>document.querySelector('[data-kind=file]')?.textContent.includes('来源预览中补充'),'Restaged reference preview is missing');
assert(true,'Source preview survives two tray transfers');
assert(errors.length===0,'The complete image, explanation and transfer workflow has no storage errors');
window.removeEventListener('ledger-storage-error',failed);
return {checks};
